import { useEffect, useState } from 'react'
import { NavLink, Outlet, useNavigate } from 'react-router-dom'
import { BarChart3, CreditCard, LayoutDashboard, LogOut, Menu, Plus, ReceiptText, Settings2, Tags, UserRound, X } from 'lucide-react'
import { logout } from '../../api/auth'
import { getProfile } from '../../api/auth'
import { clearTokens } from '../../api/client'

const links = [{ to: '/', label: 'Overview', icon: LayoutDashboard }, { to: '/transactions', label: 'Transactions', icon: ReceiptText }, { to: '/accounts', label: 'Accounts', icon: CreditCard }, { to: '/categories', label: 'Categories', icon: Tags }, { to: '/analytics', label: 'Analytics', icon: BarChart3 }]
export default function Layout() {
  const [open, setOpen] = useState(false); const navigate = useNavigate(); const profile = JSON.parse(localStorage.getItem('ledgerly_profile') || '{}')
  useEffect(() => { const handler = () => navigate('/login'); window.addEventListener('ledgerly:logout', handler); getProfile().then(profile => localStorage.setItem('ledgerly_profile', JSON.stringify(profile))).catch(() => {}); return () => window.removeEventListener('ledgerly:logout', handler) }, [navigate])
  const signOut = async () => { try { await logout(localStorage.getItem('refresh')) } catch {} clearTokens(); navigate('/login') }
  return <div className="app-shell"><aside className={`sidebar ${open ? 'is-open' : ''}`}><div className="sidebar-brand"><span className="logo-mark">L</span><strong>ledgerly</strong><button className="icon-button sidebar-close" onClick={() => setOpen(false)} aria-label="Close navigation"><X size={19} /></button></div><nav className="nav-list">{links.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} end={to === '/'} onClick={() => setOpen(false)} className={({ isActive }) => isActive ? 'nav-link active' : 'nav-link'}><Icon size={18} />{label}</NavLink>)}</nav><div className="sidebar-footer"><NavLink to="/profile" className="nav-link" onClick={() => setOpen(false)}><UserRound size={18} />Profile</NavLink><button className="nav-link logout-link" onClick={signOut}><LogOut size={18} />Log out</button><div className="user-mini"><span className="avatar">{(profile.first_name || profile.username || 'U').slice(0, 1).toUpperCase()}</span><span><strong>{profile.first_name || profile.username || 'Your profile'}</strong><small>Personal workspace</small></span><Settings2 size={16} /></div></div></aside><main className="main-content"><header className="mobile-top"><button className="icon-button" onClick={() => setOpen(true)} aria-label="Open navigation"><Menu size={21} /></button><div className="mobile-brand"><span className="logo-mark">L</span><strong>ledgerly</strong></div><button className="icon-button" onClick={() => navigate('/transactions')} aria-label="Add transaction"><Plus size={21} /></button></header><Outlet /></main><nav className="bottom-nav">{links.slice(0, 2).map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} end={to === '/'}><Icon size={19} /><span>{label}</span></NavLink>)}<button onClick={() => navigate('/transactions')} aria-label="Add transaction"><Plus size={22} /></button><NavLink to="/accounts"><CreditCard size={19} /><span>Accounts</span></NavLink><NavLink to="/profile"><UserRound size={19} /><span>Profile</span></NavLink></nav>{open && <button className="sidebar-scrim" onClick={() => setOpen(false)} aria-label="Close navigation" />}</div>
}
