# Generated by Django 5.2.15 on 2026-09-02 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_financeaccount_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='financeaccount',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_category_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='financeaccount',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_account_name_per_user'),
        ),
    ]
