# Generated by Django 5.2.15 on 2026-09-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_description_alter_financeaccount_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
