import { useState } from 'react'
import { ArrowRight, CheckCircle2, LockKeyhole, Sparkles } from 'lucide-react'
import { changeInfo, login, requestNewCode, signup, verifyCode } from '../api/auth'
import { getApiError } from '../api/client'

const blank = { user_input: '', password: '', email_or_phone_number: '', code: '', first_name: '', last_name: '', username: '', conf_password: '' }
export default function AuthPage({ initialStep = 'login' }) {
  const [step, setStep] = useState(initialStep); const [form, setForm] = useState(blank); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [codeHint, setCodeHint] = useState('')
  const update = e => setForm(current => ({ ...current, [e.target.name]: e.target.value }))
  const submit = async e => { e.preventDefault(); setBusy(true); setError(''); try {
    if (step === 'login') { await login({ user_input: form.user_input, password: form.password }); window.location.href = '/' }
    if (step === 'signup') { const data = await signup({ email_or_phone_number: form.email_or_phone_number }); setCodeHint(data.verification_code || ''); setForm(current => ({ ...current, code: data.verification_code || '' })); setStep('verify') }
    if (step === 'verify') { await verifyCode(form.code); setStep('profile') }
    if (step === 'profile') { const data = await changeInfo({ first_name: form.first_name, last_name: form.last_name, username: form.username, password: form.password, conf_password: form.conf_password }); localStorage.setItem('ledgerly_profile', JSON.stringify({ ...form, ...(data.user || {}) })); window.location.href = '/' }
  } catch (requestError) { setError(getApiError(requestError)) } finally { setBusy(false) } }
  const title = { login: 'Your money, in focus.', signup: 'A clearer way to spend.', verify: 'One last security check.', profile: 'Make Ledgerly yours.' }[step]
  const description = { login: 'A calm home for every account, income and expense.', signup: 'Start with an email or phone number. You can finish the details next.', verify: 'Enter the four-digit code sent to your contact.', profile: 'Add your details to unlock your personal finance workspace.' }[step]
  return <main className="auth-page"><aside className="auth-aside"><div className="brand-lockup"><span className="logo-mark">L</span><strong>ledgerly</strong></div><div className="auth-aside-copy"><p className="kicker">Personal finance, made legible</p><h2>All your money. One steady view.</h2><p>Track the choices that shape your month, without the noise.</p></div><div className="auth-quote"><Sparkles size={16} /> Built for the small decisions that add up.</div></aside><section className="auth-card"><div className="mobile-brand brand-lockup"><span className="logo-mark">L</span><strong>ledgerly</strong></div><div className="auth-card-head"><span className="icon-badge"><LockKeyhole size={17} /></span><p className="kicker">{step === 'login' ? 'Welcome back' : 'Create your workspace'}</p><h1>{title}</h1><p>{description}</p></div><form onSubmit={submit} className="form-stack">
    {step === 'login' && <><Field label="Username, email or phone"><input name="user_input" required value={form.user_input} onChange={update} autoComplete="username" placeholder="you@example.com" /></Field><Field label="Password"><input name="password" required type="password" value={form.password} onChange={update} autoComplete="current-password" placeholder="Password" /></Field></>}
    {step === 'signup' && <Field label="Email or phone number"><input name="email_or_phone_number" required value={form.email_or_phone_number} onChange={update} autoComplete="email" placeholder="you@example.com" /></Field>}
    {step === 'verify' && <><Field label="4-digit verification code"><input name="code" required inputMode="numeric" pattern="[0-9]{4}" maxLength="4" value={form.code} onChange={update} placeholder="0000" /></Field>{codeHint && <p className="dev-hint"><CheckCircle2 size={15} /> Development code: {codeHint}</p>}<button type="button" className="quiet-button" disabled={busy} onClick={async () => { try { const data = await requestNewCode(); setCodeHint(data.verification_code || '') } catch (requestError) { setError(getApiError(requestError)) } }}>Send a new code</button></>}
    {step === 'profile' && <><div className="form-grid"><Field label="First name"><input name="first_name" required value={form.first_name} onChange={update} /></Field><Field label="Last name"><input name="last_name" required value={form.last_name} onChange={update} /></Field></div><Field label="Username"><input name="username" required value={form.username} onChange={update} /></Field><div className="form-grid"><Field label="Password"><input name="password" required type="password" value={form.password} onChange={update} /></Field><Field label="Confirm password"><input name="conf_password" required type="password" value={form.conf_password} onChange={update} /></Field></div></>}
    {error && <div className="error-message">{error}</div>}<button className="primary-button wide" disabled={busy}>{busy ? 'Please wait…' : step === 'login' ? 'Sign in' : step === 'profile' ? 'Open my workspace' : step === 'verify' ? 'Verify code' : 'Create account'} <ArrowRight size={17} /></button>
  </form><button className="auth-switch" onClick={() => { setError(''); setStep(step === 'login' ? 'signup' : 'login') }}>{step === 'login' ? 'New to Ledgerly? Create an account' : 'Already have an account? Sign in'}</button></section></main>
}
function Field({ label, children }) { return <label className="field-label">{label}{children}</label> }
